Repository ImMin5/CULIFE, pull requests merged in 2022-05, with the labels that each got.

#25 [FEAT]BOTTOM 작성
  src/main/webapp/WEB-INF/inc/bottom.jspf
  src/main/webapp/css/top_bottom.css
Labels: 기능개발

#26 [FEAT]home > section1 완성
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/css/top_bottom.css
  src/main/webapp/img/main_visual_1.jpg
  src/main/webapp/img/main_visual_1.png
  src/main/webapp/js/home_main_visual.js
Labels: 기능개발

#27 [FEAT]home > section2 완성
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/css/top_bottom.css
  src/main/webapp/img/home_entertain_movie.jpg
  src/main/webapp/img/home_entertain_musical.jpg
  src/main/webapp/img/home_visual2.png
Labels: 기능개발

#22 영화/연극 API불러오기 및 기초작업
  src/main/java/com/team/culife/controller/CultureController.java
  src/main/java/com/team/culife/dao/CultureDAO.java
  src/main/java/com/team/culife/service/CultureService.java
  src/main/java/com/team/culife/service/CultureServiceImpl.java
  src/main/java/com/team/culife/vo/CultureVO.java
  src/main/resources/mapper/cultureMapper.xml
  src/main/webapp/WEB-INF/views/theater/theaterList.jsp
  src/main/webapp/css/theater/theaterList.css
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#30 mypage.jsp에 top.jspf 적용
  src/main/webapp/WEB-INF/views/member/mypage.jsp
Labels: 기능개발

#35 로그인 뷰 페이지 top.jspf 적용
  src/main/java/com/team/culife/controller/LoginController.java
  src/main/webapp/WEB-INF/views/login/login.jsp
Labels: 기능개발

#37 [FEAT] home > 스크롤 기능 추가
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
Labels: 기능개발

#34 작가 팔로우/언팔로우 기능 추가
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/dao/AuthorDAO.java
  src/main/java/com/team/culife/dao/MemberDAO.java
  src/main/java/com/team/culife/service/AuthorService.java
  src/main/java/com/team/culife/service/AuthorServiceImpl.java
  src/main/java/com/team/culife/service/MemberService.java
  src/main/java/com/team/culife/service/MemberServiceImpl.java
  src/main/java/com/team/culife/vo/AuthorFanVO.java
  src/main/java/com/team/culife/vo/AuthorVO.java
  src/main/java/com/team/culife/vo/MemberVO.java
  src/main/resources/mapper/authorMapper.xml
  src/main/resources/mapper/memberMapper.xml
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/img/login/kakao_login_large_narrow.png
  src/main/webapp/img/login/kakao_login_medium_wide.png
Labels: 기능개발

#40 [FIX] 메인페이지 로그인 연결 해결
  src/main/webapp/WEB-INF/views/home.jsp
Labels: 기능개발

#42 [FEAT]home > 마이페이지 추가
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/css/home.css
  src/main/webapp/css/top_bottom.css
  src/main/webapp/img/mypage_icon_b.png
  src/main/webapp/img/mypage_icon_w.png
Labels: 기능개발

#44 [FEAT] 팔로잉 작가 뷰 페이지
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/dao/MemberDAO.java
  src/main/java/com/team/culife/service/MemberService.java
  src/main/java/com/team/culife/service/MemberServiceImpl.java
  src/main/java/com/team/culife/vo/PageResponseBody.java
  src/main/java/com/team/culife/vo/PagingVO.java
  src/main/resources/mapper/memberMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/css/mypage/mypage.css
  src/main/webapp/css/mypage/mypage_fan.css
  src/main/webapp/img/member/search.png
Labels: 기능개발

#43 [STYLE] 로그인 페이지 로고 및 로그인 버튼 수정
  src/main/webapp/WEB-INF/views/login/login.jsp
  src/main/webapp/img/login/culife_logo.png
Labels: 기능개발

#47 [FEAT]home > section3 완성
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/img/home_exhibition_bg.png
  src/main/webapp/img/home_exhibition_img1.png
  src/main/webapp/img/home_exhibition_img2.png
  src/main/webapp/img/home_exhibition_img3.png
  src/main/webapp/img/home_exhibition_img4.png
  src/main/webapp/img/home_exhibition_img5.png
  src/main/webapp/img/home_exhibition_img6.png
  src/main/webapp/js/home.js
Labels: 기능개발

#48 [FIX]home > section2 css 수정
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
Labels: 기능개발

#52 [FIX]home > css 배율 수정
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/js/home.js
Labels: 기능개발

#54 [FEAT] 영화메인페이지, 영화서브페이지 작성
  src/main/java/com/team/culife/controller/MovieController.java
  src/main/webapp/WEB-INF/views/movie/movieList.jsp
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
Labels: 기능개발

#55 [FIX]home > button:hover 버그 수정
  src/main/webapp/css/home.css
Labels: 버그

#56 [Comment] Top.jsp 에 폰트어썸 cdn링크추가
  src/main/webapp/WEB-INF/inc/top.jspf
Labels: 기능개발

#58 [FEAT] 영화View페이지 주요출연진 추가
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
Labels: 기능개발

#59 [FEAT]home > section2 오디오 추가
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/img/Reality - From La Boum_cut.mp3
  src/main/webapp/img/웃는남자_일단와_cut.mp3
  src/main/webapp/js/home.js
Labels: 기능개발

#60 작가 등록 페이지 수정
  src/main/java/com/team/culife/controller/ExhibitionController.java
  src/main/java/com/team/culife/controller/MovieController.java
  src/main/java/com/team/culife/dao/AuthorDAO.java
  src/main/java/com/team/culife/dao/ExhibitionDAO.java
  src/main/java/com/team/culife/service/AuthorService.java
  src/main/java/com/team/culife/service/AuthorServiceImpl.java
  src/main/java/com/team/culife/service/ExhibitionService.java
  src/main/java/com/team/culife/service/ExhibitionServiceImpl.java
  src/main/java/com/team/culife/vo/ExhibitionVO.java
  src/main/resources/application.yml
  src/main/resources/mapper/authorMapper.xml
  src/main/resources/mapper/exhibitionMapper.xml
  src/main/resources/mybatis-config.xml
  src/main/webapp/WEB-INF/views/exhibition/authorView.jsp
  src/main/webapp/WEB-INF/views/exhibition/authorWrite.jsp
  src/main/webapp/WEB-INF/views/exhibition/exhibitionView.jsp
  src/main/webapp/WEB-INF/views/exhibition/exhibitionWrite.jsp
  src/main/webapp/WEB-INF/views/exhibition/workCreate.jsp
  src/main/webapp/WEB-INF/views/exhibition/workEdit.jsp
  src/main/webapp/css/exhibition/authorWrite.css
Labels: 기능개발

#62 [FIX] home > section2 오디오 볼륨 다운
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/img/Reality - From La Boum_cut.mp3
  src/main/webapp/img/웃는남자_일단와_cut.mp3
Labels: 버그

#63 연극/뮤지컬 상세페이지 지도 추가
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#65 마이페이지 - 리뷰(영화) 작성
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/vo/PagingVO.java
  src/main/resources/mapper/memberMapper.xml
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/member/mypage.jsp
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
  src/main/webapp/css/mypage/mypage_movie.css
Labels: 버그, 기능개발

#66 [FEAT]home > section4 틀
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/css/top_bottom.css
  src/main/webapp/js/home.js
Labels: 기능개발

#67 [FIX] mypage.css 수정 및 PagingVO 수정
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/vo/PagingVO.java
  src/main/webapp/css/mypage/mypage.css
Labels: 버그

#69 Feature/mypage review new
  src/main/java/com/team/culife/controller/ExhibitionController.java
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/service/AuthorServiceImpl.java
  src/main/webapp/WEB-INF/views/exhibition/authorWrite.jsp
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/css/exhibition/authorWrite.css
Labels: 버그, 기능개발

#71 [STYLE] authorWrite.jsp 오타 수정 '}' 빠짐
  src/main/webapp/WEB-INF/views/exhibition/authorWrite.jsp
Labels: 버그

#77 [FEAT]영화메인페이지-박스슬라이더추가, 역대흥행작추가
  src/main/webapp/WEB-INF/views/movie/movieList.jsp
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/img/movie/bg.png
Labels: 기능개발

#74 [FEAT]마이페이지 - 작성글 페이지
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/webapp/WEB-INF/views/mypage/my_board.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/css/mypage/mypage.css
  src/main/webapp/css/mypage/mypage_board.css
  src/main/webapp/css/mypage/mypage_movie.css
Labels: 기능개발

#79 마이페이지 - 리뷰(영화) 검색 및 페이지네이션
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/dao/MovieDAO.java
  src/main/java/com/team/culife/service/MovieReviewService.java
  src/main/java/com/team/culife/service/MovieReviewServiceImpl.java
  src/main/java/com/team/culife/service/MovieService.java
  src/main/java/com/team/culife/service/MovieServiceImpl.java
  src/main/resources/mapper/movieMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
Labels: 기능개발

#81 [FEAT]온라인 전시회 메인페이지 작성
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/webapp/WEB-INF/inc/bottom.jspf
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/exhibition/authorView.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorList.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorView.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/css/top_bottom.css
  src/main/webapp/img/exhibition/arrow_left.png
  src/main/webapp/img/exhibition/arrow_right.png
  src/main/webapp/img/exhibition/close.png
  src/main/webapp/img/exhibition/frame.png
  src/main/webapp/img/exhibition/magnifying_glass.png
  src/main/webapp/img/exhibition/online_exhibition_bg.png
  src/main/webapp/img/exhibition/painting_frame_skew.png
  src/main/webapp/img/exhibition/painting_frame_skew_shadow.png
  src/main/webapp/img/exhibition/room.png
  src/main/webapp/img/exhibition/test_img.jpg
  src/main/webapp/img/exhibition/test_img_1.jpg
Labels: 기능개발

#82 [STYLE] review container width 조절 74vh->70vh
  src/main/webapp/css/mypage/mypage_movie.css
Labels: 기능개발

#83 작가등록페이지 수정
  src/main/java/com/team/culife/controller/ExhibitionController.java
  src/main/java/com/team/culife/vo/AuthorVO.java
  src/main/java/com/team/culife/vo/ExhibitionVO.java
  src/main/resources/mapper/authorMapper.xml
  src/main/webapp/WEB-INF/views/exhibition/authorView.jsp
  src/main/webapp/WEB-INF/views/exhibition/authorWrite.jsp
  src/main/webapp/WEB-INF/views/exhibition/exhibitionWrite.jsp
  src/main/webapp/css/exhibition/authorWrite.css
  src/main/webapp/upload/1/thumbnail/넷이셀카.png
Labels: 기능개발

#84 Feature/movie
  src/main/webapp/WEB-INF/views/movie/movieList.jsp
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#86 [STYLE]top/bottom css 수정
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/top_bottom.css
Labels: 기능개발

#87 페이지네이션 줄바꿈 수정
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
Labels: 버그

#93 [STYLE] 영화메인페이지-top.jspf header중복태그제거
  src/main/webapp/WEB-INF/views/movie/movieList.jsp
Labels: 기능개발

#95 [STYLE] TOP css 변경, 폰트 변경
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/top_bottom.css
  src/main/webapp/img/gnb_zigzag_bg_r.png
Labels: 기능개발

#98 [FEAT] 영화검색페이지 추가
  src/main/java/com/team/culife/controller/MovieController.java
  src/main/webapp/WEB-INF/views/movie/movieList.jsp
  src/main/webapp/WEB-INF/views/movie/movieSearch.jsp
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/css/movie/movieSearch.css
Labels: 기능개발

#99 [FEAT]온라인전시회 > 전시등록 모달 작성
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/exibition_reg.css
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/img/exhibition/ex_reg/0.jpg
  src/main/webapp/img/exhibition/ex_reg/1.jpg
  src/main/webapp/img/exhibition/ex_reg/2.jpg
  src/main/webapp/img/exhibition/ex_reg/3.jpg
  src/main/webapp/img/exhibition/ex_reg/4.jpg
  src/main/webapp/img/exhibition/ex_reg/5.jpg
  src/main/webapp/img/exhibition/ex_reg/6.jpg
  src/main/webapp/img/exhibition/ex_reg/7.jpg
  src/main/webapp/img/exhibition/ex_reg/8.jpg
  src/main/webapp/img/exhibition/zigzag_bg.png
  src/main/webapp/js/modal.js
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#100 [STYLE] 영화 검색페이지 css 변경
  src/main/webapp/css/movie/movieSearch.css
Labels: 기능개발

#101 [STYLE] top, bottom, home 구성 변경
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/css/top_bottom.css
  src/main/webapp/js/home.js
Labels: 기능개발

#102 [STYLE] 영화검색페이지 유효성체크
  src/main/webapp/WEB-INF/views/movie/movieList.jsp
  src/main/webapp/WEB-INF/views/movie/movieSearch.jsp
  src/main/webapp/css/movie/movieSearch.css
Labels: 기능개발

#106 [FIX]마이페이지 - 영화리뷰 검색시 totalRecord 초기화 수정
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/dao/MovieDAO.java
  src/main/java/com/team/culife/service/MovieReviewService.java
  src/main/java/com/team/culife/service/MovieReviewServiceImpl.java
  src/main/java/com/team/culife/service/MovieService.java
  src/main/java/com/team/culife/service/MovieServiceImpl.java
  src/main/resources/mapper/movieMapper.xml
Labels: 버그

#110 [FEAT] 마이페이지 - 연극/뮤지컬 리뷰 검색 기능
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/dao/ReviewDAO.java
  src/main/java/com/team/culife/service/ReviewService.java
  src/main/java/com/team/culife/service/ReviewServiceImpl.java
  src/main/resources/mapper/reviewMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_theater.jsp
  src/main/webapp/css/mypage/mypage.css
Labels: 기능개발

#112 [FEAT]온라인전시회 > 작품등록 모달 작성
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/img/exhibition/marble_bg.png
  src/main/webapp/js/modal.js
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#114 [FEAT]작가목록 프론트 완성
  src/main/java/com/team/culife/controller/CultureController.java
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorList.jsp
  src/main/webapp/css/exhibition/authorList.css
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/js/authorList.js
Labels: 기능개발

#116 [FEAT] review table 변경에 따른 mapper 수정
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/resources/mapper/reviewMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_theater.jsp
Labels: 기능개발

#94 [FEAT]Feature/board DB불러오기 작업중
  src/main/java/com/team/culife/controller/BoardController.java
  src/main/java/com/team/culife/dao/BoardDAO.java
  src/main/java/com/team/culife/service/BoardService.java
  src/main/java/com/team/culife/service/BoardServiceImpl.java
  src/main/java/com/team/culife/vo/BoardVO.java
  src/main/java/com/team/culife/vo/PagingVO.java
  src/main/resources/mapper/boardMapper.xml
  src/main/webapp/WEB-INF/inc/bottom.jspf
  src/main/webapp/WEB-INF/views/board/freeBoardList.jsp
  src/main/webapp/WEB-INF/views/board/freeBoardView.jsp
  src/main/webapp/WEB-INF/views/board/freeBoardWrite.jsp
  src/main/webapp/WEB-INF/views/board/helpBoardList.jsp
  src/main/webapp/WEB-INF/views/board/helpBoardView.jsp
  src/main/webapp/WEB-INF/views/board/helpBoardWrite.jsp
  src/main/webapp/css/board/board.css
  src/main/webapp/css/board/boardViewReply.css
  src/main/webapp/css/board/freeBoardView.css
  src/main/webapp/css/board/freeBoardWrite.css
  src/main/webapp/js/board/freeBoardWrite.js
Labels: 기능개발

#117 [FIX] 관리자페이지 css, 검색기능 수정
  src/main/java/com/team/culife/controller/AdminController.java
  src/main/java/com/team/culife/dao/AdminDAO.java
  src/main/java/com/team/culife/service/AdminService.java
  src/main/java/com/team/culife/service/AdminServiceImpl.java
  src/main/resources/mapper/adminMapper.xml
  src/main/webapp/WEB-INF/views/admin/adminBoardList.jsp
  src/main/webapp/WEB-INF/views/admin/adminExReplyList.jsp
  src/main/webapp/WEB-INF/views/admin/adminHelpList.jsp
  src/main/webapp/WEB-INF/views/admin/adminTop.jspf
  src/main/webapp/WEB-INF/views/admin/authorList.jsp
  src/main/webapp/css/adminPage.css
Labels: 버그, 기능개발

#118 [FEAT] 마이페이지 - 작성글 검색 및 페이지네이션 기능 추가
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/dao/BoardDAO.java
  src/main/java/com/team/culife/service/BoardService.java
  src/main/java/com/team/culife/service/BoardServiceImpl.java
  src/main/java/com/team/culife/vo/PagingVO.java
  src/main/resources/mapper/boardMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_board.jsp
  src/main/webapp/css/mypage/mypage_board.css
Labels: 기능개발

#121 [FIX] 마이페이지 - 작성글, 다른사람 작성글 불러오는 에러 해결
  src/main/resources/mapper/boardMapper.xml
Labels: 기능개발

#120 [FEAT] 정지된 아이디 로그인 불가
  src/main/java/com/team/culife/controller/LoginController.java
  src/main/java/com/team/culife/dao/MemberDAO.java
  src/main/java/com/team/culife/service/MemberService.java
  src/main/java/com/team/culife/service/MemberServiceImpl.java
  src/main/java/com/team/culife/vo/MemberVO.java
  src/main/resources/mapper/memberMapper.xml
  src/main/webapp/WEB-INF/views/login/login.jsp
Labels: 기능개발

#123 [FEAT]작가목록 상세페이지 프론트 완성
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorList.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorView.jsp
  src/main/webapp/css/exhibition/authorList.css
  src/main/webapp/css/exhibition/authorView.css
  src/main/webapp/js/authorView.js
  src/main/webapp/js/modal.js
Labels: 기능개발

#124 [STYLE] 디자인 수정
  src/main/webapp/WEB-INF/views/movie/movieList.jsp
  src/main/webapp/WEB-INF/views/movie/movieSearch.jsp
  src/main/webapp/css/movie/movieSearch.css
Labels: 기능개발

#125 스포체크 / 별점평균 / 리뷰개수
  src/main/java/com/team/culife/controller/ReviewController.java
  src/main/java/com/team/culife/dao/ReviewDAO.java
  src/main/java/com/team/culife/service/ReviewService.java
  src/main/java/com/team/culife/service/ReviewServiceImpl.java
  src/main/java/com/team/culife/vo/ReviewVO.java
  src/main/resources/mapper/reviewMapper.xml
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/img/theater/sstar.png
Labels: 기능개발

#126 [STYLE]관리자 로그인 top 배경색 변경, home 우측 pagination 버튼 크기 고정
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/css/home.css
Labels: 기능개발

#127 [FIX] 마이페이지 - 게시글 페이지네이션 오류 해결
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/resources/mapper/boardMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_board.jsp
Labels: 기능개발

#131 [FEAT] 관리자페이지-게시글링크(게시판미완)
  src/main/java/com/team/culife/vo/AdminReviewVO.java
  src/main/resources/mapper/adminMapper.xml
  src/main/webapp/WEB-INF/views/admin/adminExReplyList.jsp
  src/main/webapp/WEB-INF/views/admin/adminHelpList.jsp
  src/main/webapp/WEB-INF/views/admin/adminReviewList.jsp
  src/main/webapp/WEB-INF/views/admin/adminTop.jspf
  src/main/webapp/WEB-INF/views/admin/adminWarningList.jsp
  src/main/webapp/WEB-INF/views/admin/memberList.jsp
  src/main/webapp/css/adminPage.css
Labels: 기능개발

#133 [FEAT] 마이페이지 - 감상평 뷰페이지 작성
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
Labels: 기능개발

#135 [FEAT] 관리자 로그인시 리다이렉트 페이지 설정
  src/main/java/com/team/culife/controller/LoginController.java
Labels: 기능개발

#136 [FEAT] 마이페이지-작가 신청 이미지 파일 업로드 기능
  src/main/java/com/team/culife/controller/ExhibitionController.java
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/resources/mapper/authorMapper.xml
  src/main/webapp/WEB-INF/views/exhibition/authorWrite.jsp
Labels: 기능개발

#137 [FEAT]작가목록 db연결, 페이징
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/java/com/team/culife/dao/AuthorDAO.java
  src/main/java/com/team/culife/service/AuthorService.java
  src/main/java/com/team/culife/service/AuthorServiceImpl.java
  src/main/java/com/team/culife/vo/PagingVO.java
  src/main/resources/mapper/authorMapper.xml
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorList.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorView.jsp
  src/main/webapp/css/exhibition/authorList.css
  src/main/webapp/css/exhibition/authorView.css
  src/main/webapp/js/authorList.js
  src/main/webapp/upload/1/author/thumbnail/gnb_zigzag_bg.png
Labels: 기능개발

#138 [FEAT] 평점 프론트 완료
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
Labels: 기능개발

#141 신고기능 추가
  src/main/java/com/team/culife/controller/ReviewController.java
  src/main/java/com/team/culife/service/ReviewServiceImpl.java
  src/main/java/com/team/culife/vo/ReviewVO.java
  src/main/resources/mapper/reviewMapper.xml
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
Labels: 기능개발

#144 [STYLE] css 파일 분리
  src/main/webapp/WEB-INF/views/movie/movieList.jsp
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/css/movie/movieList.css
  src/main/webapp/css/movie/movieView.css
Labels: 기능개발

#145 [FIX] 관리자페이지 - 신고관리수정
  src/main/java/com/team/culife/vo/AdminReviewVO.java
  src/main/resources/mapper/adminMapper.xml
  src/main/webapp/WEB-INF/views/admin/adminReviewList.jsp
  src/main/webapp/WEB-INF/views/admin/adminTop.jspf
  src/main/webapp/WEB-INF/views/admin/adminWarningList.jsp
  src/main/webapp/css/adminPage.css
Labels: 기능개발

#146 [FIX] 마이페이지 - 작가정보 데이터 불러오지 않는 오류 수정
  src/main/java/com/team/culife/controller/ExhibitionController.java
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/webapp/js/online_exhibition.js
Labels: 버그

#148 [STYLE]온라인 전시회 css 수정
  src/main/webapp/css/exhibition/authorList.css
  src/main/webapp/css/exhibition/authorView.css
  src/main/webapp/css/exhibition/onlineList.css
Labels: 기능개발

#154 [FEAT] 작가 상세정보 작품 표시
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/java/com/team/culife/dao/ExhibitionDAO.java
  src/main/java/com/team/culife/service/ExhibitionService.java
  src/main/java/com/team/culife/service/ExhibitionServiceImpl.java
  src/main/java/com/team/culife/vo/WorkVO.java
  src/main/resources/mapper/exhibitionMapper.xml
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorView.jsp
  src/main/webapp/js/authorView.js
Labels: 기능개발

#157 [FEAT] 로그인 인터셉터 기능 추가
  src/main/java/com/team/culife/config/WebConfig.java
  src/main/java/com/team/culife/intercepter/AdminInterceptor.java
  src/main/java/com/team/culife/intercepter/AuthorInterceptor.java
  src/main/java/com/team/culife/intercepter/LoginInterceptor.java
  src/main/webapp/WEB-INF/views/admin/adminBoardList.jsp
  src/main/webapp/WEB-INF/views/admin/adminExReplyList.jsp
  src/main/webapp/WEB-INF/views/admin/adminHelpList.jsp
  src/main/webapp/WEB-INF/views/admin/adminWarningList.jsp
  src/main/webapp/WEB-INF/views/admin/authorList.jsp
  src/main/webapp/WEB-INF/views/admin/memberList.jsp
  src/main/webapp/css/adminPage.css
Labels: 기능개발

#158 [FEAT] 작품등록 css 변경
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#159 [FEAT] 온라인전시 - 작품등록 삭제 새로고침x
  src/main/java/com/team/culife/service/ExhibitionServiceImpl.java
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#161 [STYLE] 온라인전시 - 작가목록 이미지 경로 수정
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorList.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
Labels: 기능개발

#166 [STYLE] 연극/공연 List페이지 css
  src/main/webapp/WEB-INF/views/theater/theaterList.jsp
  src/main/webapp/css/theater/theaterList.css
  src/main/webapp/img/theater/BackBack.png
  src/main/webapp/img/theater/Backg.png
Labels: 기능개발

#167 [STYLE] css 수정
  src/main/webapp/css/theater/theaterList.css
Labels: 기능개발

#171 마이페이지 - 작가정보 -> 위치조정 및 textarea 글자수 제한
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/css/mypage/mypage.css
Labels: 기능개발

#173 [FEAT] 관리자페이지 상단 이미지추가
  src/main/webapp/WEB-INF/views/admin/adminBoardList.jsp
  src/main/webapp/WEB-INF/views/admin/adminExReplyList.jsp
  src/main/webapp/WEB-INF/views/admin/adminHelpList.jsp
  src/main/webapp/WEB-INF/views/admin/adminReviewList.jsp
  src/main/webapp/WEB-INF/views/admin/adminWarningList.jsp
  src/main/webapp/WEB-INF/views/admin/authorList.jsp
  src/main/webapp/WEB-INF/views/admin/memberList.jsp
  src/main/webapp/css/adminPage.css
  src/main/webapp/img/admin/1.jpg
  src/main/webapp/img/admin/2.jpg
  src/main/webapp/img/admin/3.jpg
  src/main/webapp/img/admin/4.jpg
  src/main/webapp/img/admin/5.jpg
  src/main/webapp/img/admin/6.jpg
  src/main/webapp/img/admin/7.jpg
Labels: 기능개발

#175 [REFACT] 페이징 처리 수정
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/webapp/WEB-INF/views/mypage/my_board.jsp
  src/main/webapp/css/mypage/mypage_board.css
Labels: 기능개발

#177 [FEAT] 온라인 전시회 - 작가상세 정보 팔로우/언팔로우 기능 추가
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorView.jsp
  src/main/webapp/js/authorView.js
Labels: 기능개발

#179 [STYLE] 연극/공연페이지 CSS 수정
  src/main/webapp/WEB-INF/views/theater/theaterList.jsp
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/css/theater/theaterView.css
  src/main/webapp/img/theater/star.png
  src/main/webapp/img/theater/star_3.SVG
Labels: 기능개발

#162 [FEAT] 영화 리뷰
  .classpath
  src/main/java/com/team/culife/controller/MovieController.java
  src/main/java/com/team/culife/controller/MovieReviewController.java
  src/main/java/com/team/culife/controller/MovieWarningController.java
  src/main/java/com/team/culife/dao/MovieReviewDAO.java
  src/main/java/com/team/culife/dao/MovieWarningDAO.java
  src/main/java/com/team/culife/service/MovieReviewService.java
  src/main/java/com/team/culife/service/MovieReviewServiceImpl.java
  src/main/java/com/team/culife/service/MovieWarningService.java
  src/main/java/com/team/culife/service/MovieWarningServiceImpl.java
  src/main/java/com/team/culife/vo/MovieReviewVO.java
  src/main/java/com/team/culife/vo/MovieWarningVO.java
  src/main/resources/mapper/movieReviewMapper.xml
  src/main/resources/mapper/movieWarningMapper.xml
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/css/movie/movieView.css
Labels: 기능개발

#181 [FEAT]온라인전시회 작품보기 이미지 zoom-in 기능 추가
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/onlineList.css
Labels: 기능개발

#182 [FEAT] 온라인전시회 페이징<->View 연결
  src/main/java/com/team/culife/controller/MovieWarningController.java
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/resources/mapper/exhibitionMapper.xml
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorList.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/js/authorList.js
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#183 [FEAT] 온라인 전시회 감상평 - 수정중
  src/main/java/com/team/culife/controller/ExhibitionReviewController.java
  src/main/java/com/team/culife/dao/ExhibitionDAO.java
  src/main/java/com/team/culife/dao/ExhibitionReviewDAO.java
  src/main/java/com/team/culife/service/ExhibitionReviewService.java
  src/main/java/com/team/culife/service/ExhibitionReviewServiceImpl.java
  src/main/java/com/team/culife/service/ExhibitionService.java
  src/main/java/com/team/culife/service/ExhibitionServiceImpl.java
  src/main/java/com/team/culife/vo/ExhibitionReviewVO.java
  src/main/java/com/team/culife/vo/ExhibitionVO.java
  src/main/resources/mapper/exhibition_reviewMapper.xml
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorList.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/onlineList.css
Labels: 기능개발

#185 [STYLE] 작가상세페이지 팔로우 버튼 CSS
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorView.jsp
  src/main/webapp/css/exhibition/authorView.css
  src/main/webapp/js/authorView.js
Labels: 기능개발

#184 [FEAT] 영화 평점 기능 추
  src/main/java/com/team/culife/controller/MovieController.java
  src/main/resources/mapper/movieWarningMapper.xml
  src/main/webapp/WEB-INF/views/movie/movieList.jsp
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/css/movie/movieView.css
Labels: 기능개발

#190 [FEAT] 관리자페이지 CSS변경
  src/main/java/com/team/culife/controller/AdminController.java
  src/main/java/com/team/culife/controller/BoardController.java
  src/main/java/com/team/culife/controller/LoginController.java
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/webapp/WEB-INF/views/admin/adminBoardList.jsp
  src/main/webapp/WEB-INF/views/admin/adminExReplyList.jsp
  src/main/webapp/WEB-INF/views/admin/adminHelpList.jsp
  src/main/webapp/WEB-INF/views/admin/adminReviewList.jsp
  src/main/webapp/WEB-INF/views/admin/adminWarningList.jsp
  src/main/webapp/WEB-INF/views/admin/authorList.jsp
  src/main/webapp/WEB-INF/views/admin/memberList.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/css/adminPage.css
  src/main/webapp/img/admin/noanswer1.jpg
  src/main/webapp/img/admin/page_next.png
  src/main/webapp/img/admin/page_nnext.png
  src/main/webapp/img/admin/page_pprev.png
  src/main/webapp/img/admin/page_prev.png
Labels: 기능개발

#194 [FEAT] top, home 텍스트 변경 (연극/뮤지컬--> 공연)
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/css/top_bottom.css
Labels: 기능개발

#195 [FEAT]검색 결과없음 추가했음.
  src/main/java/com/team/culife/controller/BoardController.java
  src/main/java/com/team/culife/vo/PagingVO.java
  src/main/resources/mapper/boardMapper.xml
  src/main/webapp/WEB-INF/inc/bottom.jspf
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/board/boardWriteSuc.jsp
  src/main/webapp/WEB-INF/views/board/freeBoardList.jsp
  src/main/webapp/WEB-INF/views/board/freeBoardView.jsp
  src/main/webapp/WEB-INF/views/board/help/helpBoardList.jsp
  src/main/webapp/WEB-INF/views/board/help/helpBoardView.jsp
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/css/board/board.css
  src/main/webapp/css/board/freeBoardEdit.css
  src/main/webapp/css/board/freeBoardView.css
  src/main/webapp/css/board/freeBoardWrite.css
  src/main/webapp/css/board/helpBoardEdit.css
  src/main/webapp/css/board/helpBoardView.css
  src/main/webapp/css/board/helpBoardWrite.css
  src/main/webapp/js/board/freeBoardWrite.js
Labels: 기능개발

#196 [STYLE] 온라인 전시회 감상평 CSS
  src/main/resources/mapper/exhibition_reviewMapper.xml
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#197 [STYLE] 작가등록신청 css 깨짐 --> 변경완료
  src/main/webapp/WEB-INF/views/exhibition/authorWrite.jsp
  src/main/webapp/css/exhibition/authorWrite.css
  src/main/webapp/css/mypage/mypage.css
Labels: 기능개발

#198 [STYLE] 영화리뷰수정폼 디자인 수정
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/css/movie/movieView.css
Labels: 기능개발

#186 [FEAT] 마이페이지 - 알림기능 추가
  src/main/java/com/team/culife/controller/ExhibitionController.java
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/java/com/team/culife/dao/AlertDAO.java
  src/main/java/com/team/culife/dao/ExhibitionReviewDAO.java
  src/main/java/com/team/culife/service/AlertService.java
  src/main/java/com/team/culife/service/AlertServiceImpl.java
  src/main/java/com/team/culife/service/ExhibitionReviewService.java
  src/main/java/com/team/culife/service/ExhibitionReviewServiceImpl.java
  src/main/java/com/team/culife/vo/AlertVO.java
  src/main/java/com/team/culife/vo/ExhibitionReviewVO.java
  src/main/resources/mapper/alertMapper.xml
  src/main/resources/mapper/exhibitionMapper.xml
  src/main/resources/mapper/exhibition_reviewMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
  src/main/webapp/WEB-INF/views/mypage/my_theater.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/js/mypage/my_review.js
Labels: 기능개발

#201 [FEAT]관리자페이지CSS, 인터셉터, 스케줄러 수정
  src/main/java/com/team/culife/CulifeApplication.java
  src/main/java/com/team/culife/Scheduler.java
  src/main/java/com/team/culife/config/WebConfig.java
  src/main/java/com/team/culife/controller/AdminController.java
  src/main/java/com/team/culife/dao/AdminDAO.java
  src/main/java/com/team/culife/intercepter/AdminInterceptor.java
  src/main/java/com/team/culife/intercepter/AuthorInterceptor.java
  src/main/java/com/team/culife/intercepter/LoginInterceptor.java
  src/main/java/com/team/culife/service/AdminService.java
  src/main/java/com/team/culife/service/AdminServiceImpl.java
  src/main/resources/mapper/adminMapper.xml
  src/main/webapp/WEB-INF/views/admin/adminBoardList.jsp
  src/main/webapp/WEB-INF/views/admin/adminHelpList.jsp
  src/main/webapp/WEB-INF/views/admin/authorList.jsp
  src/main/webapp/WEB-INF/views/admin/memberList.jsp
  src/main/webapp/css/adminPage.css
Labels: 버그, 기능개발

#202 [FEAT] 온라인 전시회 검색 CSS 작성
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/img/exhibition/texture_img.png
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#204 [FEAT] 작가승인/ 취소시 알림추가
  src/main/java/com/team/culife/controller/AdminController.java
  src/main/webapp/WEB-INF/views/admin/authorList.jsp
Labels: 기능개발

#206 [FEAT] home > 자유게시판, 문의사항 db/경로 연결
  src/main/java/com/team/culife/HomeController.java
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/css/home.css
  src/main/webapp/js/home.js
Labels: 기능개발

#207 [FEAT] 마이페이지 - 감상평 댓글 수정 기능 추가
  src/main/java/com/team/culife/controller/ExhibitionReviewController.java
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/resources/mapper/exhibition_reviewMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
Labels: 기능개발

#208 [FEAT] 마이페이지 전체 알림 적용
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/vo/PageResponseBody.java
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/my_board.jsp
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
  src/main/webapp/WEB-INF/views/mypage/my_theater.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
Labels: 기능개발

#209 [STYLE] 마이페이지 - 알림 기능 .js 파일 추가
  src/main/webapp/js/mypage/alert.js
Labels: 기능개발

#212 [FEAT] 감상평관리 댓글창 확장
  src/main/webapp/WEB-INF/views/admin/adminExReplyList.jsp
  src/main/webapp/css/adminPage.css
Labels: 기능개발

#214 [STYLE] 영화리뷰페이지:신고버튼수정
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/css/movie/movieView.css
Labels: 기능개발

#215 Feature/theater
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
Labels: 버그, 기능개발

#216 [STYLE] 연극/뮤지컬페이지 리뷰폼 스타일 적용
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#217 [STYLE] 연극/뮤지컬페이지 수정폼 디자인 적용
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#218 [FEAT] 온라인 전시회 페이징 ajax 비동기처리
  src/main/java/com/team/culife/controller/OnlineExhibitionController.java
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#220 [FEAT] 온라인 리스트 감상평 수정
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
Labels: 기능개발

#222 [FEAT] 문의사항 오류수정 완료
  src/main/webapp/WEB-INF/views/board/freeBoardList.jsp
  src/main/webapp/WEB-INF/views/board/help/helpBoardList.jsp
  src/main/webapp/WEB-INF/views/board/help/helpBoardView.jsp
  src/main/webapp/css/board/board.css
  src/main/webapp/css/board/freeBoardView.css
  src/main/webapp/css/board/helpBoardView.css
Labels: 버그

#224 [FEAT] 커뮤니티 최종파일
  src/main/webapp/WEB-INF/views/board/freeBoardEdit.jsp
  src/main/webapp/WEB-INF/views/board/freeBoardWrite.jsp
  src/main/webapp/WEB-INF/views/board/help/helpBoardEdit.jsp
  src/main/webapp/WEB-INF/views/board/help/helpBoardWrite.jsp
  src/main/webapp/css/board/freeBoardEdit.css
  src/main/webapp/css/board/freeBoardWrite.css
  src/main/webapp/css/board/helpBoardEdit.css
  src/main/webapp/css/board/helpBoardWrite.css
Labels: 기능개발

#226 [FEAT] 온라인 전시회 전시회 감상평 호출 오류 수정
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/js/online_exhibition.js
  src/main/webapp/upload/3/author/exhibition/14/1.jpg
  src/main/webapp/upload/3/author/exhibition/14/2.jpg
  src/main/webapp/upload/6/author/exhibition/2/1.jpg
  src/main/webapp/upload/6/author/exhibition/2/2.jpg
Labels: 기능개발

#227 [STYLE] 연극/뮤지컬페이지 background-image px 수정
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#229 [FIX]관리자페이지 링크-새탭으로 변경
  src/main/webapp/WEB-INF/views/admin/adminBoardList.jsp
  src/main/webapp/WEB-INF/views/admin/adminHelpList.jsp
  src/main/webapp/WEB-INF/views/admin/adminTop.jspf
Labels: 기능개발

#230 [STYLE] 연극/뮤지컬 신고버튼 디자인 수정
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#211 [FEAT] File 업로드를 위한 FileService 기능 추가
  src/main/java/com/team/culife/config/WebConfig.java
  src/main/java/com/team/culife/controller/ExhibitionController.java
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/service/FileService.java
  src/main/resources/application.yml
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#231 [STYLE]home > 로그인 후 메인페이지 View 변경
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/home.css
  src/main/webapp/js/home.js
Labels: 기능개발

#234 [STYLE] 마이페이지 - 사이드바 이름 안뜨는거 수정
  2.pngstar.png
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/webapp/WEB-INF/views/exhibition/authorWrite.jsp
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/my_board.jsp
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
  src/main/webapp/WEB-INF/views/mypage/my_theater.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/js/mypage/alert.js
  src/main/webapp/upload/10/author/exhibition/9/2.jpg
  src/main/webapp/upload/10/author/thumbnail/4.PNG
  src/main/webapp/upload/11/author/exhibition/10/3.jpg
  src/main/webapp/upload/11/author/thumbnail/4.PNG
  src/main/webapp/upload/12/author/exhibition/11/4.jpg
  src/main/webapp/upload/12/author/exhibition/11/5.jpg
  src/main/webapp/upload/12/author/thumbnail/1.PNG
  src/main/webapp/upload/13/author/exhibition/12/6.jpg
  src/main/webapp/upload/13/author/exhibition/12/7.jpg
  src/main/webapp/upload/13/author/exhibition/12/8.jpg
  src/main/webapp/upload/13/author/thumbnail/1.PNG
  src/main/webapp/upload/3/author/exhibition/14/1.jpg
  src/main/webapp/upload/3/author/exhibition/14/2.jpg
  src/main/webapp/upload/3/author/thumbnail/2.PNG
  src/main/webapp/upload/4/author/exhibition/3/1.jpg
  src/main/webapp/upload/4/author/exhibition/3/3.jpg
  src/main/webapp/upload/4/author/exhibition/3/4.jpg
  src/main/webapp/upload/4/author/thumbnail/1.PNG
  src/main/webapp/upload/5/author/exhibition/4/1.jpg
  src/main/webapp/upload/5/author/exhibition/4/5.jpg
  src/main/webapp/upload/5/author/thumbnail/3.PNG
  src/main/webapp/upload/6/author/exhibition/2/1.jpg
  src/main/webapp/upload/6/author/exhibition/2/2.jpg
  src/main/webapp/upload/6/author/exhibition/5/3.jpg
  src/main/webapp/upload/6/author/thumbnail/4.PNG
  src/main/webapp/upload/7/author/exhibition/6/4.jpg
  src/main/webapp/upload/7/author/exhibition/6/5.jpg
  src/main/webapp/upload/7/author/thumbnail/1.PNG
  src/main/webapp/upload/8/author/exhibition/7/1.jpg
  src/main/webapp/upload/8/author/exhibition/7/6.jpg
  src/main/webapp/upload/8/author/exhibition/7/8.jpg
  src/main/webapp/upload/8/author/thumbnail/2.PNG
  src/main/webapp/upload/9/author/exhibition/8/1.jpg
  src/main/webapp/upload/9/author/exhibition/8/3.jpg
  src/main/webapp/upload/9/author/thumbnail/3.PNG
Labels: 버그

#235 [FEAT]마이페이지 - 작가 신청, 재신청 alert 메세지 추가
  src/main/java/com/team/culife/controller/AdminController.java
  src/main/java/com/team/culife/controller/ExhibitionController.java
  src/main/resources/mapper/alertMapper.xml
  src/main/webapp/WEB-INF/views/exhibition/authorWrite.jsp
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/my_board.jsp
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
  src/main/webapp/css/exhibition/authorWrite.css
Labels: 기능개발

#237 [STYLE] 영화페이지 margin 수정
  src/main/webapp/css/movie/movieView.css
Labels: 기능개발

#238 [STYLE] 연극/뮤지컬 페이지 px 수정, hr태그 추가
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#239 [STYLE]마이페이지 - 소셜 로그아웃 uri 변경
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
Labels: 기능개발

#244 [CHORE] 로그아웃 uri 환경변수 설정
  src/main/java/com/team/culife/controller/ExhibitionController.java
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/resources/application.yml
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/my_board.jsp
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
  src/main/webapp/WEB-INF/views/mypage/my_theater.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
Labels: 문서

#245 [STYLE]마이페이지 - 로그아웃 path 변경
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/css/mypage/mypage.css
Labels: 문서

#246 [FEAT]스포일러 리뷰 기능 추가/css수정
  src/main/java/com/team/culife/controller/CultureController.java
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/css/movie/movieView.css
  src/main/webapp/css/theater/theaterView.css
  src/main/webapp/upload/1/author/b_531Ud018svcqx2edk6ghaen_axdmqd.jpg
  src/main/webapp/upload/1/author/exhibition/1/1.jpg
Labels: 기능개발

#247 Feature/theater
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/upload/1/author/b_531Ud018svcqx2edk6ghaen_axdmqd.jpg
Labels: 버그

#248 [FEAT]최종 리뷰 수정...
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/css/movie/movieView.css
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#249 [STYLE]마이페이지 - 영화,연극 리뷰 카드 크기 조절
  src/main/webapp/css/mypage/mypage.css
Labels: 스타일

#250 [STYLE]커뮤니티 입장시 연극영화top쪽 css수정
  src/main/webapp/WEB-INF/views/board/boardEditSuc.jsp
  src/main/webapp/css/board/board.css
Labels: 버그, 기능개발

#252 [STYLE] 영화페이지 리뷰 글넘침 수정, 신고버튼 CSS 수정
  src/main/webapp/css/movie/movieView.css
Labels: 스타일

#253 [FIX]문의사항 css 수정
  src/main/webapp/css/board/board.css
Labels: 버그

#254 [STYLE] 공연페이지 리뷰 글넘침 수정, 신고버튼 CSS 수정
  src/main/webapp/css/theater/theaterView.css
Labels: 스타일

#255 [STYLE] 공연페이지 스포일러, 리뷰보기 margin 수정
  src/main/webapp/WEB-INF/views/theater/theaterView.jsp
  src/main/webapp/css/theater/theaterView.css
Labels: 스타일

#256 [STYLE]공연페이지 리뷰보기 margin 수정
  src/main/webapp/css/theater/theaterView.css
Labels: 스타일

#257 [STYLE] 영화페이지 스포일러, 리뷰 CSS수정
  src/main/webapp/WEB-INF/views/movie/movieView.jsp
  src/main/webapp/css/movie/movieView.css
Labels: 스타일

#258 [STYLE] 공연페이지 리뷰 길었을 때 리뷰창 width 수정
  src/main/webapp/css/theater/theaterView.css
Labels: 스타일

#259 [FEAT] 온라인전시회 - 작가상세정보 팔로워 숫자 표시
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/dao/MemberDAO.java
  src/main/java/com/team/culife/service/MemberService.java
  src/main/java/com/team/culife/service/MemberServiceImpl.java
  src/main/resources/mapper/authorMapper.xml
  src/main/resources/mapper/memberMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
  src/main/webapp/WEB-INF/views/mypage/my_theater.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorView.jsp
  src/main/webapp/css/exhibition/authorView.css
  src/main/webapp/js/authorView.js
Labels: 버그, 기능개발

#261 [FEAT] 비로그인 문의사항 수정
  src/main/java/com/team/culife/controller/BoardController.java
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/board/freeBoardView.jsp
  src/main/webapp/WEB-INF/views/board/help/message.jsp
Labels: 버그

#262 [STYLE] 마이페이지 - 알림창 CSS 변경
  src/main/resources/mapper/authorMapper.xml
  src/main/webapp/WEB-INF/views/exhibition/authorWrite.jsp
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/my_board.jsp
  src/main/webapp/WEB-INF/views/mypage/my_fan.jsp
  src/main/webapp/WEB-INF/views/mypage/my_movie.jsp
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
  src/main/webapp/WEB-INF/views/mypage/my_theater.jsp
  src/main/webapp/WEB-INF/views/mypage/mypage.jsp
  src/main/webapp/css/mypage/mypage.css
  src/main/webapp/js/mypage/alert.js
Labels: 스타일

#242 [STYLE] 마이페이지 > 온라인 전시회 감상평 css 수정
  src/main/resources/mapper/exhibitionMapper.xml
  src/main/webapp/WEB-INF/inc/top.jspf
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/login/login.jsp
  src/main/webapp/WEB-INF/views/mypage/my_author.jsp
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/css/home.css
  src/main/webapp/css/mypage/mypage.css
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발

#263 [STYLE] 마이페이지 - 감상평 줄 맞춤
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
  src/main/webapp/css/mypage/mypage.css
Labels: 스타일

#264 [STYLE] 커뮤니티 View css 구성 변경
  src/main/webapp/WEB-INF/views/board/freeBoardView.jsp
  src/main/webapp/WEB-INF/views/board/help/helpBoardView.jsp
  src/main/webapp/css/board/board.css
  src/main/webapp/css/board/freeBoardView.css
  src/main/webapp/css/board/helpBoardView.css
  src/main/webapp/upload/1/author/exhibition/1/1.jpg
Labels: 기능개발

#266 [FIX]문의사항 관리자만 댓글달기
  src/main/webapp/WEB-INF/views/board/help/helpBoardView.jsp
Labels: 버그

#270 [STYLE] cursor 빠진 부분 추가
  src/main/webapp/css/board/board.css
  src/main/webapp/css/movie/movieView.css
  src/main/webapp/css/mypage/mypage.css
  src/main/webapp/css/theater/theaterView.css
Labels: 기능개발

#271 [FEAT] 작가 상세 페이지 SNS 주소 추가
  src/main/webapp/WEB-INF/views/online_exhibition/onlineAuthorView.jsp
  src/main/webapp/css/exhibition/authorView.css
Labels: 기능개발

#272 [FEAT]마이페이지 - 나의 전시회 페이징
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/resources/mapper/exhibitionMapper.xml
  src/main/webapp/WEB-INF/views/mypage/my_exhibition.jsp
  src/main/webapp/css/mypage/mypage.css
  src/main/webapp/js/mypage/alert.js
Labels: 기능개발

#274 [FEAT]마이페이지 작성글 z-index 수정
  src/main/webapp/WEB-INF/views/mypage/my_exhibition.jsp
Labels: 스타일

#277 [FIX] 관리자페이지 css수정
  src/main/webapp/css/adminPage.css
Labels: 기능개발

#275 [STLYE & FEAT] 온라인 전시회 - 검색 결과창 위치 이동, 커뮤티니 - 게시물 댓글수 표시
  src/main/java/com/team/culife/controller/MemberController.java
  src/main/java/com/team/culife/controller/ReplyController.java
  src/main/java/com/team/culife/vo/BoardVO.java
  src/main/resources/mapper/boardMapper.xml
  src/main/webapp/WEB-INF/views/board/freeBoardList.jsp
  src/main/webapp/WEB-INF/views/board/help/helpBoardView.jsp
  src/main/webapp/WEB-INF/views/mypage/my_review.jsp
  src/main/webapp/WEB-INF/views/online_exhibition/onlineList.jsp
  src/main/webapp/css/board/freeBoardView.css
  src/main/webapp/css/board/helpBoardView.css
  src/main/webapp/css/exhibition/onlineList.css
  src/main/webapp/js/mypage/alert.js
  src/main/webapp/js/online_exhibition.js
Labels: 기능개발, 스타일

#279 [FIX]관리자페이지 css수정2
  src/main/webapp/css/adminPage.css
Labels: 기능개발
